services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./db.development.sqlite:/usr/src/app/db.development.sqlite

  nginx:
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express-app
